# --- CONFIGURACIÓN DE SUPABASE (COMENTADA CUANDO SE USA DOCKER COMPOSE) ---
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.wuoisxcquqphorevtpqn
spring.datasource.password=Chispi123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.baseline-on-migrate=true
spring.flyway.properties.flyway.postgresql.use-prepared-statements=false

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Configuración del Pool de Conexiones
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1

# JWT Configuration
jwt.secret=aVeryLongAndSecureSecretKeyThatIsAtLeast256BitsLongForHS256
jwt.expiration=86400000
# 24 hours in milliseconds

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.info.build.enabled=true

# --- CONFIGURACIÓN PARA DOCKER COMPOSE (SOBREESCRITA POR VARIABLES DE ENTORNO) ---
# Estas propiedades serán sobreescritas por las variables de entorno en docker-compose.yml
# spring.datasource.url=jdbc:postgresql://db:5432/eventhub
# spring.datasource.username=user
# spring.datasource.password=password
